### ISSUE TITLE
UI doesn't allow for 0 Royalty Percentage

### ISSUE THREAD

**Issue by sk33z3r** [you3h/LooPyGen_Client#1]
![image](https://user-images.githubusercontent.com/20587571/164759031-49f3a48d-18d2-48ec-a925-426b9f473b0b.png)

Users should be able to input `0` for a royalty percentage.

Only the LRC UI is broken and doesn't accept a value of 0, otherwise the Mint API handles it just fine.

**Comment by sk33z3r** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React UI Updates needed for Local Release](https://trello.com/c/XocuDY35/23-react-ui-updates-needed-for-local-release)

**Comment by you3h** [comment]
Applied a fix to this issue under PR #[11](https://github.com/you3h/LooPyGen_Client/pull/11)

**Comment by sk33z3r** [comment]
Works for me now
