### ISSUE TITLE
Rounded white rectangle in top-left

### ISSUE THREAD

**Issue by sk33z3r** [you3h/LooPyGen_Client#10]
Maybe this is meant to be a placeholder for a logo?

![image](https://user-images.githubusercontent.com/20587571/164761914-96e36038-f294-44ad-a9d9-803554b407e7.png)

**Comment by sk33z3r** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React UI Updates needed for Local Release](https://trello.com/c/XocuDY35/23-react-ui-updates-needed-for-local-release)

**Comment by you3h** [comment]
@sk33z3r yes that is correct. This is for a logo, I will update it using the logo that we have

**Comment by you3h** [comment]
Applied a fix to this issue under PR #[11](https://github.com/you3h/LooPyGen_Client/pull/11)

**Comment by sk33z3r** [comment]
Logo is there now.

Thoughts:
- The png is transparent, can we remove the white and let the dark blue show through?
- When the menu is expanded (see below screen), can you make **EZL2** larger and remove the `-` to fill the space a little better

**Comment by you3h** [comment]
![image](https://user-images.githubusercontent.com/18521848/166393476-8c0fd662-78d5-4b65-b2f3-3a78b4bc7cd5.png)
I updated it with this. let me know if you agree to this change

**Comment by sk33z3r** [comment]
Looks good to me!

**Comment by you3h** [comment]
Updated the LOGO in this commit https://github.com/you3h/LooPyGen_Client/commit/4d2efc6f48506ceb41cb9f924d9cbefca5d71f05

**Comment by sk33z3r** [comment]
Closing
