### ISSUE TITLE
Typo on Page 3

### ISSUE THREAD

**Issue by sk33z3r** [you3h/LooPyGen_Client#12]
Minor typo: `Pleas` should be `Please`

![image](https://user-images.githubusercontent.com/20587571/166295533-3f003259-1729-488e-8ea3-9132efc548db.png)

**Comment by sk33z3r** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React UI Updates needed for Local Release](https://trello.com/c/XocuDY35/23-react-ui-updates-needed-for-local-release)

**Comment by you3h** [comment]
Updated the spelling in this commit https://github.com/you3h/LooPyGen_Client/commit/4d2efc6f48506ceb41cb9f924d9cbefca5d71f05

**Comment by sk33z3r** [comment]
Confirmed, closing
