### ISSUE TITLE
Change save location for traits.json

### ISSUE THREAD

**Issue by sk33z3r** [you3h/LooPyGen_Client#16]
**NOTE**: The output directory of `config.json` is good and should not be changed. This is only for `traits.json`

With this update we are going to centralize the user's files, so all the layer sources and generated images/meta end up in one location, organized by the name of the collection.

For this change, the react UI should save the file to:
`../common/collections/<sanitized_collection_name>/config/traits.json`

**Comment by you3h** [comment]
Applied a fix for this issue under commit # https://github.com/you3h/LooPyGen_Client/commit/054d8a4f34d7c7e5f0ef648f8271076169d5a387

**Comment by sk33z3r** [comment]
Confirmed
