### ISSUE TITLE
collection_lower field should replace spaces with underscores

### ISSUE THREAD

**Issue by sk33z3r** [you3h/LooPyGen_Client#17]
Currently, the `collection_lower` field in the traits.json file is used to determine the directory name of all the saved images from the user.

When output from React, the name is lowercase but there are still spaces:

```json
	"collection_name": "SK33Z3R'S THING",
	"collection_lower": "sk33z3r's thing"
```

Instead, the sanitized `collection_lower` should strip special characters like `()/\'"` and space (` `). The first group would be just removed, but spaces should be replaced with underscores (`_`). Example:

```json
	"collection_name": "SK33Z3R'S THING",
	"collection_lower": "sk33z3rs_thing"
```

**Comment by sk33z3r** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React UI Updates needed for Local Release](https://trello.com/c/XocuDY35/23-react-ui-updates-needed-for-local-release)

**Comment by you3h** [comment]
Applied a fix for this issue under commit # https://github.com/you3h/LooPyGen_Client/commit/054d8a4f34d7c7e5f0ef648f8271076169d5a387

**Comment by sk33z3r** [comment]
Confirmed
