### ISSUE TITLE
RGBA alpha values are incorrect

### ISSUE THREAD

**Issue by sk33z3r** [you3h/LooPyGen_Client#18]
This issue is based on how the PHP UI behaves.

In RGBA, all values have a range from `0 - 255`. However, the current Alpha slider in React sets them from `0 - 1.0`

I believe that `0 - 255` is the correct range, but I need @montspy to confirm. I will try to run a test generation with the React scale to see if it works.

**Comment by sk33z3r** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React UI Updates needed for Local Release](https://trello.com/c/XocuDY35/23-react-ui-updates-needed-for-local-release)

**Comment by sk33z3r** [comment]
Monty confirmed, the Alpha value needs to be in the range `0 - 255`

**Comment by you3h** [comment]
Applied a fix for this issue under commit # https://github.com/you3h/LooPyGen_Client/commit/054d8a4f34d7c7e5f0ef648f8271076169d5a387
