### ISSUE TITLE
Default placeholders

### ISSUE THREAD

**Issue by sk33z3r** [you3h/LooPyGen_Client#4]
Default placeholders in the input fields should match the old PHP UI where possible for feature parity and to line up with wording in the wiki.

Search for `placeholder=` in the files under `config/` and `setup/` folders in the main branch:

https://github.com/sk33z3r/LooPyGen/tree/main/php/setup
https://github.com/sk33z3r/LooPyGen/tree/main/php/config

**Comment by sk33z3r** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React UI Updates needed for Local Release](https://trello.com/c/XocuDY35/23-react-ui-updates-needed-for-local-release)

**Comment by you3h** [comment]
Applied a fix to this issue under PR #[11](https://github.com/you3h/LooPyGen_Client/pull/11)

**Comment by sk33z3r** [comment]
Everything looks to be in place
