### ISSUE TITLE
Pick an actual file for filename under Trait Variation

### ISSUE THREAD

**Issue by sk33z3r** [you3h/LooPyGen_Client#5]
The old PHP UI allowed the user to select a file. This doesn't upload the file, but guarantees the filename is set accurately in the output JSON, because people suck at typing.

We should add this back in. Eventually, the field will actually upload the files and then organize them exactly how we need them.

**Comment by sk33z3r** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React UI Updates needed for Local Release](https://trello.com/c/XocuDY35/23-react-ui-updates-needed-for-local-release)

**Comment by you3h** [comment]
Applied a fix to this issue under PR #[11](https://github.com/you3h/LooPyGen_Client/pull/11)

**Comment by sk33z3r** [comment]
Implemented and working
