### ISSUE TITLE
Missing content on 3rd page of Collection Wizard

### ISSUE THREAD

**Issue by sk33z3r** [you3h/LooPyGen_Client#6]
I would expect an outline of all the details I just added after clicking NEXT to move onto step 3. Possibly even just pretty printing the JSON is enough.

**Comment by sk33z3r** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React UI Updates needed for Local Release](https://trello.com/c/XocuDY35/23-react-ui-updates-needed-for-local-release)

**Comment by you3h** [comment]
Applied a fix to this issue under PR #[11](https://github.com/you3h/LooPyGen_Client/pull/11)

**Comment by sk33z3r** [comment]
JSON output style looks good!
