### ISSUE TITLE
Change wording on final page to "traits.json" instead of "metadata.json"

### ISSUE THREAD

**Issue by sk33z3r** [you3h/LooPyGen_Client#8]
Currently the final page calls the Collection Wizard output "metadata", but this is misleading. We should clearly separate the terms.

![image](https://user-images.githubusercontent.com/20587571/164761385-78b21746-e604-4a7c-94ac-e7d417394580.png)

Output names:

* For the Collection Wizard: "Traits Data" saves to file `traits.json`
* For the Minting Config: Minting Config saves to file `config.json`

**Comment by sk33z3r** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React UI Updates needed for Local Release](https://trello.com/c/XocuDY35/23-react-ui-updates-needed-for-local-release)

**Comment by you3h** [comment]
Applied a fix to this issue under PR #[11](https://github.com/you3h/LooPyGen_Client/pull/11)

**Comment by sk33z3r** [comment]
Looks good
