### ISSUE TITLE
Remove erroneous message at the bottom of the UI

### ISSUE THREAD

**Issue by sk33z3r** [you3h/LooPyGen_Client#9]
There's a message about User Settings that appears at the bottom of the UI. I don't think means anything, but for a local release this should be removed.

![image](https://user-images.githubusercontent.com/20587571/164761770-0f016e97-86ef-4f77-b4f2-bd35472be221.png)

**Comment by sk33z3r** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React UI Updates needed for Local Release](https://trello.com/c/XocuDY35/23-react-ui-updates-needed-for-local-release)

**Comment by you3h** [comment]
Applied a fix to this issue under PR #[11](https://github.com/you3h/LooPyGen_Client/pull/11)

**Comment by sk33z3r** [comment]
I no longer see the message
